## Coolant_Pressure_TimeSeries

#### using Pyodbc

In [1]:
import pandas as pd
import numpy as np
import pyodbc
import warnings

warnings.filterwarnings("ignore")


In [2]:
pyodbc.drivers()

['SQL Server',
 'SQL Server Native Client 11.0',
 'ODBC Driver 17 for SQL Server',
 'Oracle in OracleClient19Home1_64bits',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)']

In [3]:
import pyodbc
cnxn = pyodbc.connect("Driver={SQL Server Native Client 11.0};"
                        "Server=na0vm00024.apac.bosch.com;"
                        "Database=DB_MFC2DB_SQL;"
                        "Trusted_Connection=yes;")

In [26]:
sql = """SELECT [Coolant_Set_pressure] ,[CoolantPr], [PresentTool], [ToolBroken], [ProgRun], [TimeStamp] FROM [ChironDZ9_1] WHERE Timestamp BETWEEN '2023-09-20T00:00:47' AND '2024-02-21T09:45:58'
  ORDER BY 'TimeStamp'""" 
df = pd.read_sql_query(sql, cnxn, index_col="TimeStamp", parse_dates=True)
df.head()


Coolant_Set_pressure  CoolantPr  PresentTool  \
TimeStamp                                                               
2023-09-20 17:02:30.523                   0.0  18.120365            2   
2023-09-20 17:02:30.547                   0.0  18.120365            2   
2023-09-20 17:02:31.547                   0.0  18.120365            2   
2023-09-20 17:02:32.547                   0.0  18.120365            2   
2023-09-20 17:02:33.547                   0.0  18.120365            2   

                         ToolBroken  ProgRun  
TimeStamp                                     
2023-09-20 17:02:30.523       False     True  
2023-09-20 17:02:30.547       False     True  
2023-09-20 17:02:31.547       False     True  
2023-09-20 17:02:32.547       False     True  
2023-09-20 17:02:33.547       False     True

In [27]:
df.tail()

Coolant_Set_pressure  CoolantPr  PresentTool  \
TimeStamp                                                               
2024-02-21 09:45:53.597                   0.0  43.511765            2   
2024-02-21 09:45:54.597                   0.0  43.511765            2   
2024-02-21 09:45:55.597                   0.0  43.511765            2   
2024-02-21 09:45:56.597                   0.0  43.511765            2   
2024-02-21 09:45:57.597                   0.0  43.511765            2   

                         ToolBroken  ProgRun  
TimeStamp                                     
2024-02-21 09:45:53.597       False     True  
2024-02-21 09:45:54.597       False     True  
2024-02-21 09:45:55.597       False     True  
2024-02-21 09:45:56.597       False     True  
2024-02-21 09:45:57.597       False     True

In [28]:
df_copy = df[df["ToolBroken"] & df["ProgRun"]]
df_copy

Coolant_Set_pressure  CoolantPr  PresentTool  \
TimeStamp                                                               
2023-09-21 21:15:08.650                   0.0  73.351234           22   
2023-09-21 21:15:09.650                   0.0  73.351234           22   
2023-09-21 21:15:10.650                   0.0  73.351234           22   
2023-09-21 21:15:11.650                   0.0  73.351234           22   
2023-09-21 21:15:12.650                   0.0  73.351234           22   
...                                       ...        ...          ...   
2024-02-21 09:20:14.110                   0.0  26.902065           22   
2024-02-21 09:20:15.110                   0.0  26.902065           22   
2024-02-21 09:20:16.110                   0.0  26.902065           22   
2024-02-21 09:20:17.110                   0.0  26.902065           22   
2024-02-21 09:20:18.110                   0.0  26.902065           22   

                         ToolBroken  ProgRun  
TimeStamp                                     
2023-09-21 21:15:08.650        True     True  
2023-09-21 21:15:09.650        True     True  
2023-09-21 21:15:10.650        True     True  
2023-09-21 21:15:11.650        True     True  
2023-09-21 21:15:12.650        True     True  
...                             ...      ...  
2024-02-21 09:20:14.110        True     True  
2024-02-21 09:20:15.110        True     True  
2024-02-21 09:20:16.110        True     True  
2024-02-21 09:20:17.110        True     True  
2024-02-21 09:20:18.110        True     True  

[11574 rows x 5 columns]

In [29]:
### Toolbroken during last one month
df_copy["PresentTool"].unique()

array([22,  6, 23, 12, 30, 14, 28], dtype=int64)

## Tool 22 Break Signature

In [50]:
df_copy.index = pd.to_datetime(df_copy.index)

df_copy['Date'] = df_copy.index.date
df_copy['Time'] = df_copy.index.time

df_copy

Coolant_Set_pressure  CoolantPr  PresentTool  \
TimeStamp                                                               
2023-09-21 21:15:08.650                   0.0  73.351234           22   
2023-09-21 21:15:09.650                   0.0  73.351234           22   
2023-09-21 21:15:10.650                   0.0  73.351234           22   
2023-09-21 21:15:11.650                   0.0  73.351234           22   
2023-09-21 21:15:12.650                   0.0  73.351234           22   
...                                       ...        ...          ...   
2024-02-21 09:20:14.110                   0.0  26.902065           22   
2024-02-21 09:20:15.110                   0.0  26.902065           22   
2024-02-21 09:20:16.110                   0.0  26.902065           22   
2024-02-21 09:20:17.110                   0.0  26.902065           22   
2024-02-21 09:20:18.110                   0.0  26.902065           22   

                         ToolBroken  ProgRun        Date             Time  
TimeStamp                                                                  
2023-09-21 21:15:08.650        True     True  2023-09-21  21:15:08.650000  
2023-09-21 21:15:09.650        True     True  2023-09-21  21:15:09.650000  
2023-09-21 21:15:10.650        True     True  2023-09-21  21:15:10.650000  
2023-09-21 21:15:11.650        True     True  2023-09-21  21:15:11.650000  
2023-09-21 21:15:12.650        True     True  2023-09-21  21:15:12.650000  
...                             ...      ...         ...              ...  
2024-02-21 09:20:14.110        True     True  2024-02-21  09:20:14.110000  
2024-02-21 09:20:15.110        True     True  2024-02-21  09:20:15.110000  
2024-02-21 09:20:16.110        True     True  2024-02-21  09:20:16.110000  
2024-02-21 09:20:17.110        True     True  2024-02-21  09:20:17.110000  
2024-02-21 09:20:18.110        True     True  2024-02-21  09:20:18.110000  

[11574 rows x 7 columns]

---------------------------------------------------------------------------------------------------------------------------

### For all the tools when Broken

In [55]:
df_tool = df_copy[df_copy["ToolBroken"] & df_copy["ProgRun"]]
df_tool["Date"].unique()

array([datetime.date(2023, 9, 21), datetime.date(2023, 9, 24),
       datetime.date(2023, 9, 25), datetime.date(2023, 9, 26),
       datetime.date(2023, 9, 30), datetime.date(2023, 10, 2),
       datetime.date(2023, 10, 6), datetime.date(2023, 10, 7),
       datetime.date(2023, 10, 16), datetime.date(2023, 12, 12),
       datetime.date(2023, 12, 13), datetime.date(2023, 12, 14),
       datetime.date(2023, 12, 15), datetime.date(2024, 1, 6),
       datetime.date(2024, 1, 7), datetime.date(2024, 1, 8),
       datetime.date(2024, 1, 9), datetime.date(2024, 1, 10),
       datetime.date(2024, 1, 11), datetime.date(2024, 1, 15),
       datetime.date(2024, 1, 16), datetime.date(2024, 1, 17),
       datetime.date(2024, 1, 18), datetime.date(2024, 1, 19),
       datetime.date(2024, 1, 20), datetime.date(2024, 1, 29),
       datetime.date(2024, 1, 30), datetime.date(2024, 1, 31),
       datetime.date(2024, 2, 1), datetime.date(2024, 2, 2),
       datetime.date(2024, 2, 3), datetime.date(2024, 2,

In [56]:
first_data_by_date = df_tool.groupby(df_tool['Date']).first()
first_data_by_date

Coolant_Set_pressure   CoolantPr  PresentTool  ToolBroken  \
Date                                                                    
2023-09-21                   0.0   73.351234           22        True   
2023-09-24                   0.0   74.312570            6        True   
2023-09-25                   0.0   74.243904           22        True   
2023-09-26                   0.0  119.220560           23        True   
2023-09-30                   0.0   74.365974            6        True   
2023-10-02                   0.0   74.579605            6        True   
2023-10-06                   0.0   24.437696           30        True   
2023-10-07                   0.0   41.917170           14        True   
2023-10-16                   0.0   34.119694           22        True   
2023-12-12                   0.0   75.571460            6        True   
2023-12-13                   0.0   75.785090            6        True   
2023-12-14                   0.0   80.309456           22        True   
2023-12-15                   0.0   31.105991           28        True   
2024-01-06                   0.0   78.691980            6        True   
2024-01-07                   0.0   80.614640            6        True   
2024-01-08                   0.0   77.600940           22        True   
2024-01-09                   0.0   80.553604            6        True   
2024-01-10                   0.0   79.676200           22        True   
2024-01-11                   0.0   80.179756            6        True   
2024-01-15                   0.0   82.674644            6        True   
2024-01-16                   0.0   77.082120           22        True   
2024-01-17                   0.0   80.500200           22        True   
2024-01-18                   0.0  122.432630           23        True   
2024-01-19                   0.0  120.662560           23        True   
2024-01-20                   0.0   74.907684           22        True   
2024-01-29                   0.0   71.817680           22        True   
2024-01-30                   0.0   80.721460            6        True   
2024-01-31                   0.0   72.405170           22        True   
2024-02-01                   0.0   73.381760           22        True   
2024-02-02                   0.0   73.053680            6        True   
2024-02-03                   0.0   82.255010           22        True   
2024-02-05                   0.0   82.110050           22        True   
2024-02-14                   0.0   34.775840           28        True   
2024-02-20                   0.0   45.152134           22        True   
2024-02-21                   0.0   26.902065           22        True   

            ProgRun             Time  
Date                                  
2023-09-21     True  21:15:08.650000  
2023-09-24     True  00:47:05.797000  
2023-09-25     True  11:23:23.410000  
2023-09-26     True  06:50:09.400000  
2023-09-30     True  02:38:16.113000  
2023-10-02     True  14:49:19.313000  
2023-10-06     True  09:50:46.540000  
2023-10-07     True  01:50:41.147000  
2023-10-16     True  12:09:27.637000  
2023-12-12     True  13:11:29.390000  
2023-12-13     True  00:06:45.193000  
2023-12-14     True  11:14:22.873000  
2023-12-15     True  13:15:20.287000  
2024-01-06     True  00:49:28.353000  
2024-01-07     True  03:15:14.557000  
2024-01-08     True  17:21:45.137000  
2024-01-09     True  03:53:42.683000  
2024-01-10     True  00:51:43.013000  
2024-01-11     True  13:03:01.550000  
2024-01-15     True  08:13:05.060000  
2024-01-16     True  15:44:59.117000  
2024-01-17     True  19:56:02.023000  
2024-01-18     True  13:29:37.417000  
2024-01-19     True  12:57:35.040000  
2024-01-20     True  07:21:40.347000  
2024-01-29     True  17:20:09.503000  
2024-01-30     True  10:33:33.230000  
2024-01-31     True  00:38:22.327000  
2024-02-01     True  00:12:57.997000  
2024-02-02     True  13:18:50.063000  
2024-02-03     True  02:55:11.840000  
2024-02-05     True  10

#### Count of Tool number those were broken

In [77]:
Tool_broken_occurance = first_data_by_date['PresentTool'].value_counts()
Tool_broken_occurance

22    16
6     12
23     3
28     2
30     1
14     1
Name: PresentTool, dtype: int64

-----------------------------------------------------------------------------------------------------------------------------

### Studying only tool 23

In [57]:
df_tool_23 = df_copy[df_copy["ToolBroken"] & df_copy["ProgRun"] & (df_copy["PresentTool"]==23)]
df_tool_23["Date"].unique()

array([datetime.date(2023, 9, 26), datetime.date(2023, 12, 13),
       datetime.date(2024, 1, 18), datetime.date(2024, 1, 19)],
      dtype=object)

In [59]:
tool23_by_date = df_tool_23.groupby(df_tool_23['Date']).first()
tool23_by_date

Coolant_Set_pressure  CoolantPr  PresentTool  ToolBroken  ProgRun  \
Date                                                                            
2023-09-26                   0.0  119.22056           23        True     True   
2023-12-13                   0.0  118.56441           23        True     True   
2024-01-18                   0.0  122.43263           23        True     True   
2024-01-19                   0.0  120.66256           23        True     True   

                       Time  
Date                         
2023-09-26  06:50:09.400000  
2023-12-13  03:38:59.843000  
2024-01-18  13:29:37.417000  
2024-01-19  12:57:35.040000

In [60]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2023-09-26 06:49:09.400000'
end_timestamp = '2023-09-26 06:51:09.400000'

tool23_on_26sep = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]
tool23_on_26sep["PresentTool"].unique()

array([17, 18,  0, 19, 20, 21, 22, 23], dtype=int64)

In [61]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2023-12-13 03:37:59.843000'
end_timestamp = '2023-12-13 03:39:59.843000'

tool23_on_13dec = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]
tool23_on_13dec["PresentTool"].unique()

array([17, 18,  0, 19, 20, 21, 22, 23], dtype=int64)

In [66]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-01-18 13:28:37.417000'
end_timestamp = '2024-01-18 13:30:37.417000'

tool23_on_18Jan = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]
tool23_on_18Jan["PresentTool"].unique()

array([17, 18, 19, 20,  0, 21, 22, 23], dtype=int64)

In [72]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-01-19 12:56:35.040000'
end_timestamp = '2024-01-19 12:58:35.040000'

tool23_on_19Jan = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool23_on_19Jan["PresentTool"].unique()

array([18,  0, 19, 20, 21, 22, 23], dtype=int64)

## When Tool Broken

### Signatures of Tool 23 Coolant Pressure before break

In [101]:
### Tool_23 ---> 26th Sept, 2023

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool23_on_26sep.index, y=tool23_on_26sep['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool23_on_26sep.index, y=tool23_on_26sep['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool23_on_26sep.index, tool23_on_26sep['CoolantPr'], tool23_on_26sep['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()


In [69]:
### Tool_23 ---> 13th Dec, 2023

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool23_on_13dec.index, y=tool23_on_13dec['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool23_on_13dec.index, y=tool23_on_13dec['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool23_on_13dec.index, tool23_on_13dec['CoolantPr'], tool23_on_13dec['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()

In [125]:
### Tool_23 ---> 18th Jan, 2024

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool23_on_18Jan.index, y=tool23_on_18Jan['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool23_on_18Jan.index, y=tool23_on_18Jan['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool23_on_18Jan.index, tool23_on_18Jan['CoolantPr'], tool23_on_18Jan['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()

In [126]:
### Tool_23 ---> 19th Jan, 2024

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool23_on_19Jan.index, y=tool23_on_19Jan['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool23_on_19Jan.index, y=tool23_on_19Jan['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool23_on_19Jan.index, tool23_on_19Jan['CoolantPr'], tool23_on_19Jan['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()

-------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------------------

#### Studying only tool 22

In [78]:
df_tool_22 = df_copy[df_copy["ToolBroken"] & df_copy["ProgRun"] & (df_copy["PresentTool"]==22)]
df_tool_22["Date"].unique()

array([datetime.date(2023, 9, 21), datetime.date(2023, 9, 25),
       datetime.date(2023, 10, 16), datetime.date(2023, 12, 12),
       datetime.date(2023, 12, 13), datetime.date(2023, 12, 14),
       datetime.date(2024, 1, 8), datetime.date(2024, 1, 10),
       datetime.date(2024, 1, 15), datetime.date(2024, 1, 16),
       datetime.date(2024, 1, 17), datetime.date(2024, 1, 20),
       datetime.date(2024, 1, 29), datetime.date(2024, 1, 31),
       datetime.date(2024, 2, 1), datetime.date(2024, 2, 3),
       datetime.date(2024, 2, 5), datetime.date(2024, 2, 20),
       datetime.date(2024, 2, 21)], dtype=object)

In [80]:
tool22_by_date = df_tool_22.groupby(df_tool_22['Date']).first()
tool22_by_date

Coolant_Set_pressure  CoolantPr  PresentTool  ToolBroken  ProgRun  \
Date                                                                            
2023-09-21                   0.0  73.351234           22        True     True   
2023-09-25                   0.0  74.243904           22        True     True   
2023-10-16                   0.0  34.119694           22        True     True   
2023-12-12                   0.0  80.896940           22        True     True   
2023-12-13                   0.0  81.743830           22        True     True   
2023-12-14                   0.0  80.309456           22        True     True   
2024-01-08                   0.0  77.600940           22        True     True   
2024-01-10                   0.0  79.676200           22        True     True   
2024-01-15                   0.0  81.255530           22        True     True   
2024-01-16                   0.0  77.082120           22        True     True   
2024-01-17                   0.0  80.500200           22        True     True   
2024-01-20                   0.0  74.907684           22        True     True   
2024-01-29                   0.0  71.817680           22        True     True   
2024-01-31                   0.0  72.405170           22        True     True   
2024-02-01                   0.0  73.381760           22        True     True   
2024-02-03                   0.0  82.255010           22        True     True   
2024-02-05                   0.0  82.110050           22        True     True   
2024-02-20                   0.0  45.152134           22        True     True   
2024-02-21                   0.0  26.902065           22        True     True   

                       Time  
Date                         
2023-09-21  21:15:08.650000  
2023-09-25  11:23:23.410000  
2023-10-16  12:09:27.637000  
2023-12-12  22:50:21.190000  
2023-12-13  03:47:47.993000  
2023-12-14  11:14:22.873000  
2024-01-08  17:21:45.137000  
2024-01-10  00:51:43.013000  
2024-01-15  11:55:16.780000  
2024-01-16  15:44:59.117000  
2024-01-17  19:56:02.023000  
2024-01-20  07:21:40.347000  
2024-01-29  17:20:09.503000  
2024-01-31  00:38:22.327000  
2024-02-01  00:12:57.997000  
2024-02-03  02:55:11.840000  
2024-02-05  10:19:55.397000  
2024-02-20  08:49:38.543000  
2024-02-21  09:19:39.110000

In [81]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2023-09-21 21:14:08.650000'
end_timestamp = '2023-09-21 21:16:08.650000'

tool22_on_21sep = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_21sep["PresentTool"].unique()

array([12,  0, 17, 18, 19, 20, 21, 22], dtype=int64)

In [82]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2023-09-25 11:22:23.410000'
end_timestamp = '2023-09-25 11:24:23.410000'

tool22_on_25sep = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_25sep["PresentTool"].unique()

array([12,  0, 17, 18, 19, 20, 21, 22], dtype=int64)

In [ ]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-01-20 07:20:40.347000'
end_timestamp = '2024-01-20 07:22:40.347000'

tool22_on_20Jan = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_20Jan["PresentTool"].unique()

In [95]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-02-05 10:18:55.397000'
end_timestamp = '2024-02-05 10:20:55.397000'

tool22_on_5Feb = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_5Feb["PresentTool"].unique()

array([11, 12,  0, 17, 18, 19, 20, 21, 22], dtype=int64)

In [98]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-02-20 08:48:38.543000'
end_timestamp = '2024-02-20 08:50:38.543000'

tool22_on_20Feb = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_20Feb["PresentTool"].unique()

array([ 0, 20, 21, 22], dtype=int64)

In [89]:
df.index = pd.to_datetime(df.index)

start_timestamp = '2024-02-21 09:19:38.110000'
end_timestamp = '2024-02-21 09:19:40.110000'

tool22_on_21Feb = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

# selected_data.head()
tool22_on_21Feb["PresentTool"].unique()

array([22], dtype=int64)

### Tool 22 Signature Plots

In [109]:
### Tool 22 21, sept, 2024


import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_21sep.index, y=tool22_on_21sep['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_21sep.index, y=tool22_on_21sep['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_21sep.index, tool22_on_21sep['CoolantPr'], tool22_on_21sep['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Tool 22_Coolant Set Pressure vs Coolant Pressure_21st sept,2023',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()




In [108]:
### Tool 22 ---->25th sept,2023

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_25sep.index, y=tool22_on_25sep['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_25sep.index, y=tool22_on_25sep['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_25sep.index, tool22_on_25sep['CoolantPr'], tool22_on_25sep['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Tool 22_Coolant Set Pressure vs Coolant Pressure_25st sept,2023',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()



In [116]:
### Tool 22  ---->16oct, 2024
import plotly.graph_objects as go
df.index = pd.to_datetime(df.index)

start_timestamp = '2023-10-16 12:08:57.637000'
end_timestamp = '2023-10-16 12:10:27.637000'

tool22_on_16oct = df[(df.index >= start_timestamp) & (df.index <= end_timestamp)]

trace1 = go.Scatter(x=tool22_on_16oct.index, y=tool22_on_16oct['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_16oct.index, y=tool22_on_16oct['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_16oct.index, tool22_on_16oct['CoolantPr'], tool22_on_16oct['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Tool 22_Coolant Set Pressure vs Coolant Pressure_16oct,2023',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()

In [105]:
### Tool 22 ---->20th Jan, 2024


import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_20Jan.index, y=tool22_on_20Jan['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_20Jan.index, y=tool22_on_20Jan['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_20Jan.index, tool22_on_20Jan['CoolantPr'], tool22_on_20Jan['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()


In [104]:
### Tool 22 ---->5th Feb, 2024


import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_5Feb.index, y=tool22_on_5Feb['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_5Feb.index, y=tool22_on_5Feb['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_5Feb.index, tool22_on_5Feb['CoolantPr'], tool22_on_5Feb['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()



In [103]:
### Tool 22 ---->20th Feb, 2024

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_20Feb.index, y=tool22_on_20Feb['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_20Feb.index, y=tool22_on_20Feb['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_20Feb.index, tool22_on_20Feb['CoolantPr'], tool22_on_20Feb['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()


In [102]:
### Tool 22 ---->21st Feb, 2024

import plotly.graph_objects as go

trace1 = go.Scatter(x=tool22_on_21Feb.index, y=tool22_on_21Feb['Coolant_Set_pressure'], mode='lines', name='Coolant_Set_pressure', line=dict(color='blue'))

trace2 = go.Scatter(x=tool22_on_21Feb.index, y=tool22_on_21Feb['CoolantPr'], mode='lines', name='CoolantPr', line=dict(color='red'))

annotations = []
for timestamp, coolant_pressure, present_tool in zip(tool22_on_21Feb.index, tool22_on_21Feb['CoolantPr'], tool22_on_21Feb['PresentTool']):
    annotations.append(dict(x=timestamp, y=coolant_pressure, text=f'Tool {present_tool}', showarrow=False, xanchor='center', yanchor='bottom'))


layout = go.Layout(
    title='Coolant Set Pressure vs Coolant Pressure',
    xaxis=dict(title='TimeStamp'),
    yaxis=dict(title='Value'),
    annotations=annotations
)


fig = go.Figure(data=[trace1, trace2], layout=layout)


fig.show()