In [1]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [2]:
type([1, 2, 3, 4, 5])

list

In [3]:
["Group A", "Group B", "Control Group"]

['Group A', 'Group B', 'Control Group']

In [4]:
["Group A", "Group B", "Control 'Group'"]

['Group A', 'Group B', "Control 'Group'"]

In [5]:
list_1 = [1, 2, 3, 4, 5]

In [6]:
list_1

[1, 2, 3, 4, 5]

In [7]:
len(list_1)

5

In [9]:
import numpy as np

In [10]:
np.sum(list_1) / len(list_1)

3.0

In [11]:
list_1[0]

1

In [12]:
list_1[2]

3

In [13]:
list_1[-1]

5

In [14]:
list_1[1:3]

[2, 3]

In [15]:
list_1

[1, 2, 3, 4, 5]

In [16]:
list_1.append(6)

In [17]:
list_1

[1, 2, 3, 4, 5, 6]

In [18]:
list_1

[1, 2, 3, 4, 5, 6]

In [20]:
list_1 + [7]

[1, 2, 3, 4, 5, 6, 7]

In [21]:
list_1

[1, 2, 3, 4, 5, 6]

In [22]:
list_1.remove(5)

In [23]:
list_1

[1, 2, 3, 4, 6]

In [24]:
range(10)

range(0, 10)

In [25]:
range(0, 21, 2)

range(0, 21, 2)

In [26]:
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
dict_1 = {"Pneumonia":10, "Hypertension":5, "Diabetes":4}

In [31]:
type(dict_1)

dict

In [32]:
dict_1.items()

dict_items([('Pneumonia', 10), ('Hypertension', 5), ('Diabetes', 4)])

In [33]:
dict_1.keys()

dict_keys(['Pneumonia', 'Hypertension', 'Diabetes'])

In [34]:
dict_1.values()

dict_values([10, 5, 4])

In [35]:
dict_1["Hypertension"]

5

In [36]:
dict_1.update({"Bronchitis":6})

In [37]:
dict_1

{'Bronchitis': 6, 'Diabetes': 4, 'Hypertension': 5, 'Pneumonia': 10}

In [38]:
dict_1.pop("Hypertension")

5

In [39]:
dict_1

{'Bronchitis': 6, 'Diabetes': 4, 'Pneumonia': 10}

In [40]:
dict_2 = {"Diabetes":{"IDDM":10, "NIDDM":12}, "Hypertension":12}

In [41]:
dict_2

{'Diabetes': {'IDDM': 10, 'NIDDM': 12}, 'Hypertension': 12}

In [42]:
dict_2.values()

dict_values([{'IDDM': 10, 'NIDDM': 12}, 12])